language: android

env:
  - REVIEWDOG_VERSION=0.9.11

android:
  components:
    - tools
    - build-tools-27.0.3
    - android-27
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - android-sdk-license-.+

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.gradle

before_script:
  - chmod +x deploy_bintray.sh

script:
  - ./gradlew build

after_failure:
  - curl -fSL https://github.com/haya14busa/reviewdog/releases/download/$REVIEWDOG_VERSION/reviewdog_linux_amd64 -o ./reviewdog
  - chmod +x ./reviewdog
  - find . -type f -name "*-lint.txt" -print0 | xargs -0 cat | ./reviewdog -efm="%f:%l:%c: %m" -name="ktlint" -reporter=github-pr-review

after_success:
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
  - ./deploy_bintray.sh
