version: 2

references:
  cache_key: &cache_key
    key: jars-{{ .Branch }}-{{ checksum "build.gradle.kts" }}-{{ checksum  "buildSrc/src/main/kotlin/Constants.kt" }}-{{ checksum  "gradle/wrapper/gradle-wrapper.properties" }}

jobs:
  build:
    docker:
      - image: circleci/android:api-28-alpha
      environment:
        JVM_OPTS: -Xmx3200m
        REVIEWDOG_VERSION: "0.9.11"
    steps:
      - checkout
      - restore_cache:
        <<: *cache_key
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
        name: Download Dependencies
        command: ./gradlew dependencies
      - save_cache:
        paths:
          - ~/.gradle
        <<: *cache_key
      - run:
        name: Run Kotlin Lint & Tests
        command: ./gradlew lintKotlin test
      - run:
        name: Get and Run Review Dog Checks
        command: curl -fSL https://github.com/haya14busa/reviewdog/releases/download/$REVIEWDOG_VERSION/reviewdog_linux_amd64 -o reviewdog && chmod +x ./reviewdog
      - run:
        name: Run Add_Review Shell Files
        command: ./add_review.sh
      - run:
        name: Save test results
        command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/test/.*xml" -exec cp {} ~/test-results/junit/ \;
        when: always
      - store_test_results:
        path: ~/test-results
      - store_artifacts:
        path: ~/test-results/junit