object Dependencies {
    val archLifecycle = "android.arch.lifecycle:extensions:${Versions.archLifecycleVersion}"
    val androidAppCompat = "com.android.support:appcompat-v7:${Versions.androidSupportVersion}"
    val androidAnnotation = "com.android.support:support-annotations:${Versions.androidSupportVersion}"
    val androidTestRunner = "com.android.support.test:runner:${Versions.runnerVersion}"
    val androidTestRules = "com.android.support.test:rules:${Versions.rulesVersion}"
    val androidEspressoCore = "com.android.support.test.espresso:espresso-core:${Versions.espressoVersion}"
    val androidEspressoIntents = "com.android.support.test.espresso:espresso-intents:${Versions.espressoVersion}"
    val forge = "com.github.kittinunf.forge:forge:${Versions.forgeVersion}"
    val gson = "com.google.code.gson:gson:${Versions.gsonVersion}"
    val jackson = "com.fasterxml.jackson.module:jackson-module-kotlin:${Versions.jacksonVersion}"
    val json = "org.json:json:${Versions.jsonVersion}"
    val junit = "junit:junit:${Versions.junitVersion}"
    val kotlinCoroutinesAndroid = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.kotlinCoroutinesVersion}"
    val kotlinCoroutinesJvm = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.kotlinCoroutinesVersion}"
    val kotlinStdlib = "org.jetbrains.kotlin:kotlin-stdlib:${Versions.kotlinVersion}"
    val moshi = "com.squareup.moshi:moshi-kotlin:${Versions.moshiVersion}"
    val result = "com.github.kittinunf.result:result:${Versions.resultVersion}"
    val robolectric = "org.robolectric:robolectric:${Versions.robolectricVersion}"
    val rxJavaAndroid = "io.reactivex.rxjava2:rxandroid:${Versions.rxandroidVersion}"
    val rxJavaJvm = "io.reactivex.rxjava2:rxjava:${Versions.rxjavaVersion}"
}
